### ISSUE TITLE
Internal/External VIP

### ISSUE THREAD

**Issue by christianh814** [myllynen/openshift-ha-load-balancer#3]
What if I have no "external" vip and it's all inside my internal network?

**Comment by myllynen** [comment]
It's a good question - I cannot instantly think a reason why this would not work but the devil is in details and I haven't tested this myself. IPVS/LVS does not support the scenario where VIP and real server are on the same host or real servers are using VIP but that that should not be needed here, HAProxy is used for communication between masters and otherwise you should be able to use keepalived in DR mode for handling incoming connections outside of the OCP cluster.

However, this would require you to try this out and try to find the working setup, perhaps you could start by creating the initial configuration with the playbook, then removing parts that are needed only in the two NIC setup (e.g., in iptables) and work it from there.

**Comment by myllynen** [comment]
Since this is perhaps more like a question I'll go ahead and close this ticket. Perhaps if this is an often seen scenario we could consider a new TODO list item or RFE ticket. Thanks.
